package com.globbypotato.rockhounding_chemistry.handlers;

import com.globbypotato.rockhounding_chemistry.machines.tile.TEAirCompressor;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEBufferTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TECatalystRegen;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEContainmentTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEDepositionChamberBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEDepositionChamberTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEDisposer;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEElementsCabinetBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEElementsCabinetTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEEvaporationTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEExhaustionValve;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEExtractorBalance;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEExtractorController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEExtractorInjector;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEExtractorReactor;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEExtractorStabilizer;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEFlotationTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEFluidInputTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEFluidOutputTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEFluidTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEFluidpedia;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGanController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGanExpanderBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGanExpanderTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasCondenser;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasExpander;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasHolderBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasHolderTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasPressurizer;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasPurifier;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasifierBurner;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasifierCooler;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasifierTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGaslinePump;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEHeatExchangerBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEHeatExchangerTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELabBlenderController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELabBlenderTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELabOvenChamber;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELabOvenController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELaserEmitter;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELeachingVatCollector;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELeachingVatController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELeachingVatTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMaterialCabinetBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMaterialCabinetTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMetalAlloyer;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMetalAlloyerTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMineralSizerCollector;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMineralSizerController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMineralSizerTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMultivessel;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEOrbiter;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEParticulateCollector;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPipelinePump;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPipelineValve;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPowerGenerator;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPrecipitationChamber;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPrecipitationController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPrecipitationReactor;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPressureVessel;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEProfilingBench;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPullingCrucibleBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPullingCrucibleTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPurifierCycloneBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPurifierCycloneCap;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPurifierCycloneTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEReformerController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEReformerReactor;
import com.globbypotato.rockhounding_chemistry.machines.tile.TERetentionVat;
import com.globbypotato.rockhounding_chemistry.machines.tile.TESeasoningRack;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEServer;
import com.globbypotato.rockhounding_chemistry.machines.tile.TESlurryDrum;
import com.globbypotato.rockhounding_chemistry.machines.tile.TESlurryPond;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEStirredTankBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEStirredTankOut;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEStirredTankTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TETransposer;
import com.globbypotato.rockhounding_chemistry.machines.tile.TETubularBedBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.TETubularBedController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TETubularBedLow;
import com.globbypotato.rockhounding_chemistry.machines.tile.TETubularBedMid;
import com.globbypotato.rockhounding_chemistry.machines.tile.TETubularBedTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.TETubularBedTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEWasteDumper;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEWaterPump;

import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModTileEntities {

	public static void registerTileEntities() {
		GameRegistry.registerTileEntity(TEMineralSizerController.class, new ResourceLocation(Reference.MODID, TEMineralSizerController.getName()));
		GameRegistry.registerTileEntity(TEMineralSizerTank.class, new ResourceLocation(Reference.MODID, TEMineralSizerTank.getName()));
		GameRegistry.registerTileEntity(TEPowerGenerator.class, new ResourceLocation(Reference.MODID, TEPowerGenerator.getName()));
		GameRegistry.registerTileEntity(TEMineralSizerCollector.class, new ResourceLocation(Reference.MODID, TEMineralSizerCollector.getName()));
		GameRegistry.registerTileEntity(TEFluidTank.class, new ResourceLocation(Reference.MODID, TEFluidTank.getName()));
		GameRegistry.registerTileEntity(TELabOvenController.class, new ResourceLocation(Reference.MODID, TELabOvenController.getName()));
		GameRegistry.registerTileEntity(TELabOvenChamber.class, new ResourceLocation(Reference.MODID, TELabOvenChamber.getName()));
		GameRegistry.registerTileEntity(TEFluidInputTank.class, new ResourceLocation(Reference.MODID, TEFluidInputTank.getName()));
		GameRegistry.registerTileEntity(TEFluidOutputTank.class, new ResourceLocation(Reference.MODID, TEFluidOutputTank.getName()));
		GameRegistry.registerTileEntity(TELabBlenderController.class, new ResourceLocation(Reference.MODID, TELabBlenderController.getName()));
		GameRegistry.registerTileEntity(TELabBlenderTank.class, new ResourceLocation(Reference.MODID, TELabBlenderTank.getName()));
		GameRegistry.registerTileEntity(TEProfilingBench.class, new ResourceLocation(Reference.MODID, TEProfilingBench.getName()));
		GameRegistry.registerTileEntity(TEEvaporationTank.class, new ResourceLocation(Reference.MODID, TEEvaporationTank.getName()));
		GameRegistry.registerTileEntity(TESeasoningRack.class, new ResourceLocation(Reference.MODID, TESeasoningRack.getName()));
		GameRegistry.registerTileEntity(TEServer.class, new ResourceLocation(Reference.MODID, TEServer.getName()));
		GameRegistry.registerTileEntity(TEGasExpander.class, new ResourceLocation(Reference.MODID, TEGasExpander.getName()));

		GameRegistry.registerTileEntity(TESlurryPond.class, new ResourceLocation(Reference.MODID, TESlurryPond.getName()));
		GameRegistry.registerTileEntity(TEGasifierTank.class, new ResourceLocation(Reference.MODID, TEGasifierTank.getName()));
		GameRegistry.registerTileEntity(TEGasifierCooler.class, new ResourceLocation(Reference.MODID, TEGasifierCooler.getName()));
		GameRegistry.registerTileEntity(TEGasifierBurner.class, new ResourceLocation(Reference.MODID, TEGasifierBurner.getName()));
		GameRegistry.registerTileEntity(TEGasPurifier.class, new ResourceLocation(Reference.MODID, TEGasPurifier.getName()));
		GameRegistry.registerTileEntity(TEGasPressurizer.class, new ResourceLocation(Reference.MODID, TEGasPressurizer.getName()));
		GameRegistry.registerTileEntity(TEPurifierCycloneBase.class, new ResourceLocation(Reference.MODID, TEPurifierCycloneBase.getName()));
		GameRegistry.registerTileEntity(TEPurifierCycloneTop.class, new ResourceLocation(Reference.MODID, TEPurifierCycloneTop.getName()));
		GameRegistry.registerTileEntity(TEPurifierCycloneCap.class, new ResourceLocation(Reference.MODID, TEPurifierCycloneCap.getName()));
		GameRegistry.registerTileEntity(TEParticulateCollector.class, new ResourceLocation(Reference.MODID, TEParticulateCollector.getName()));
		GameRegistry.registerTileEntity(TEPressureVessel.class, new ResourceLocation(Reference.MODID, TEPressureVessel.getName()));
		GameRegistry.registerTileEntity(TEAirCompressor.class, new ResourceLocation(Reference.MODID, TEAirCompressor.getName()));
		GameRegistry.registerTileEntity(TEHeatExchangerBase.class, new ResourceLocation(Reference.MODID, TEHeatExchangerBase.getName()));
		GameRegistry.registerTileEntity(TEHeatExchangerTop.class, new ResourceLocation(Reference.MODID, TEHeatExchangerTop.getName()));
		GameRegistry.registerTileEntity(TEGanExpanderBase.class, new ResourceLocation(Reference.MODID, TEGanExpanderBase.getName()));
		GameRegistry.registerTileEntity(TEGanExpanderTop.class, new ResourceLocation(Reference.MODID, TEGanExpanderTop.getName()));

		GameRegistry.registerTileEntity(TEGanController.class, new ResourceLocation(Reference.MODID, TEGanController.getName()));
		GameRegistry.registerTileEntity(TEGasCondenser.class, new ResourceLocation(Reference.MODID, TEGasCondenser.getName()));
		GameRegistry.registerTileEntity(TEMultivessel.class, new ResourceLocation(Reference.MODID, TEMultivessel.getName()));
		GameRegistry.registerTileEntity(TELeachingVatController.class, new ResourceLocation(Reference.MODID, TELeachingVatController.getName()));
		GameRegistry.registerTileEntity(TELeachingVatTank.class, new ResourceLocation(Reference.MODID, TELeachingVatTank.getName()));
		GameRegistry.registerTileEntity(TELeachingVatCollector.class, new ResourceLocation(Reference.MODID, TELeachingVatCollector.getName()));
		GameRegistry.registerTileEntity(TERetentionVat.class, new ResourceLocation(Reference.MODID, TERetentionVat.getName()));
		GameRegistry.registerTileEntity(TEExtractorController.class, new ResourceLocation(Reference.MODID, TEExtractorController.getName()));
		GameRegistry.registerTileEntity(TEExtractorReactor.class, new ResourceLocation(Reference.MODID, TEExtractorReactor.getName()));
		GameRegistry.registerTileEntity(TEElementsCabinetBase.class, new ResourceLocation(Reference.MODID, TEElementsCabinetBase.getName()));
		GameRegistry.registerTileEntity(TEElementsCabinetTop.class, new ResourceLocation(Reference.MODID, TEElementsCabinetTop.getName()));
		GameRegistry.registerTileEntity(TEExtractorInjector.class, new ResourceLocation(Reference.MODID, TEExtractorInjector.getName()));
		GameRegistry.registerTileEntity(TEExtractorBalance.class, new ResourceLocation(Reference.MODID, TEExtractorBalance.getName()));
		GameRegistry.registerTileEntity(TEReformerController.class, new ResourceLocation(Reference.MODID, TEReformerController.getName()));
		GameRegistry.registerTileEntity(TEReformerReactor.class, new ResourceLocation(Reference.MODID, TEReformerReactor.getName()));
		GameRegistry.registerTileEntity(TEExtractorStabilizer.class, new ResourceLocation(Reference.MODID, TEExtractorStabilizer.getName()));

		GameRegistry.registerTileEntity(TEMetalAlloyer.class, new ResourceLocation(Reference.MODID, TEMetalAlloyer.getName()));
		GameRegistry.registerTileEntity(TEMetalAlloyerTank.class, new ResourceLocation(Reference.MODID, TEMetalAlloyerTank.getName()));
		GameRegistry.registerTileEntity(TEMaterialCabinetBase.class, new ResourceLocation(Reference.MODID, TEMaterialCabinetBase.getName()));
		GameRegistry.registerTileEntity(TEMaterialCabinetTop.class, new ResourceLocation(Reference.MODID, TEMaterialCabinetTop.getName()));
		GameRegistry.registerTileEntity(TEDepositionChamberBase.class, new ResourceLocation(Reference.MODID, TEDepositionChamberBase.getName()));
		GameRegistry.registerTileEntity(TEDepositionChamberTop.class, new ResourceLocation(Reference.MODID, TEDepositionChamberTop.getName()));
		GameRegistry.registerTileEntity(TEGasHolderBase.class, new ResourceLocation(Reference.MODID, TEGasHolderBase.getName()));
		GameRegistry.registerTileEntity(TEGasHolderTop.class, new ResourceLocation(Reference.MODID, TEGasHolderTop.getName()));
		GameRegistry.registerTileEntity(TEPullingCrucibleBase.class, new ResourceLocation(Reference.MODID, TEPullingCrucibleBase.getName()));
		GameRegistry.registerTileEntity(TEPullingCrucibleTop.class, new ResourceLocation(Reference.MODID, TEPullingCrucibleTop.getName()));
		GameRegistry.registerTileEntity(TEOrbiter.class, new ResourceLocation(Reference.MODID, TEOrbiter.getName()));
		GameRegistry.registerTileEntity(TETransposer.class, new ResourceLocation(Reference.MODID, TETransposer.getName()));
		GameRegistry.registerTileEntity(TEFluidpedia.class, new ResourceLocation(Reference.MODID, TEFluidpedia.getName()));
		GameRegistry.registerTileEntity(TEWasteDumper.class, new ResourceLocation(Reference.MODID, TEWasteDumper.getName()));
		GameRegistry.registerTileEntity(TEFlotationTank.class, new ResourceLocation(Reference.MODID, TEFlotationTank.getName()));
		GameRegistry.registerTileEntity(TEContainmentTank.class, new ResourceLocation(Reference.MODID, TEContainmentTank.getName()));

		GameRegistry.registerTileEntity(TELaserEmitter.class, new ResourceLocation(Reference.MODID, TELaserEmitter.getName()));
		GameRegistry.registerTileEntity(TEExhaustionValve.class, new ResourceLocation(Reference.MODID, TEExhaustionValve.getName()));
		GameRegistry.registerTileEntity(TEWaterPump.class, new ResourceLocation(Reference.MODID, TEWaterPump.getName()));
		GameRegistry.registerTileEntity(TECatalystRegen.class, new ResourceLocation(Reference.MODID, TECatalystRegen.getName()));
		GameRegistry.registerTileEntity(TEDisposer.class, new ResourceLocation(Reference.MODID, TEDisposer.getName()));
		GameRegistry.registerTileEntity(TESlurryDrum.class, new ResourceLocation(Reference.MODID, TESlurryDrum.getName()));
		GameRegistry.registerTileEntity(TEBufferTank.class, new ResourceLocation(Reference.MODID, TEBufferTank.getName()));
		GameRegistry.registerTileEntity(TEStirredTankBase.class, new ResourceLocation(Reference.MODID, TEStirredTankBase.getName()));
		GameRegistry.registerTileEntity(TEStirredTankTop.class, new ResourceLocation(Reference.MODID, TEStirredTankTop.getName()));
		GameRegistry.registerTileEntity(TEStirredTankOut.class, new ResourceLocation(Reference.MODID, TEStirredTankOut.getName()));
		GameRegistry.registerTileEntity(TEPrecipitationController.class, new ResourceLocation(Reference.MODID, TEPrecipitationController.getName()));
		GameRegistry.registerTileEntity(TEPrecipitationChamber.class, new ResourceLocation(Reference.MODID, TEPrecipitationChamber.getName()));
		GameRegistry.registerTileEntity(TEPrecipitationReactor.class, new ResourceLocation(Reference.MODID, TEPrecipitationReactor.getName()));

		GameRegistry.registerTileEntity(TETubularBedBase.class, new ResourceLocation(Reference.MODID, TETubularBedBase.getName()));
		GameRegistry.registerTileEntity(TETubularBedLow.class, new ResourceLocation(Reference.MODID, TETubularBedLow.getName()));
		GameRegistry.registerTileEntity(TETubularBedMid.class, new ResourceLocation(Reference.MODID, TETubularBedMid.getName()));
		GameRegistry.registerTileEntity(TETubularBedTop.class, new ResourceLocation(Reference.MODID, TETubularBedTop.getName()));
		GameRegistry.registerTileEntity(TETubularBedTank.class, new ResourceLocation(Reference.MODID, TETubularBedTank.getName()));
		GameRegistry.registerTileEntity(TETubularBedController.class, new ResourceLocation(Reference.MODID, TETubularBedController.getName()));

		GameRegistry.registerTileEntity(TEPipelinePump.class, new ResourceLocation(Reference.MODID, TEPipelinePump.getName()));
		GameRegistry.registerTileEntity(TEPipelineValve.class, new ResourceLocation(Reference.MODID, TEPipelineValve.getName()));
		GameRegistry.registerTileEntity(TEGaslinePump.class, new ResourceLocation(Reference.MODID, TEGaslinePump.getName()));
	}
}