package com.globbypotato.rockhounding_chemistry.handlers;

import com.globbypotato.rockhounding_chemistry.machines.tile.TEDepositionController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEExtractorController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGanController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasCondenserController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasExpanderController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasPurifierController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEGasifierController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEHeatExchangerController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELabBlenderController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELabOvenController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TELeachingVatController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMetalAlloyerController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEMineralSizerController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPlanningTable;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPowderMixerController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPrecipitationController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEProfilingBench;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEPullingCrucibleController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEReformerController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TERetentionVatController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEShredderController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TESlurryPondController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TEStirredTankController;
import com.globbypotato.rockhounding_chemistry.machines.tile.TETubularBedController;
import com.globbypotato.rockhounding_chemistry.machines.tile.collateral.TEAirCompressor;
import com.globbypotato.rockhounding_chemistry.machines.tile.collateral.TECatalystRegen;
import com.globbypotato.rockhounding_chemistry.machines.tile.collateral.TEElementsCabinetBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.collateral.TEElementsCabinetTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.collateral.TEFluidpedia;
import com.globbypotato.rockhounding_chemistry.machines.tile.collateral.TEMaterialCabinetBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.collateral.TEMaterialCabinetTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.collateral.TEServer;
import com.globbypotato.rockhounding_chemistry.machines.tile.devices.TEDisposer;
import com.globbypotato.rockhounding_chemistry.machines.tile.devices.TEOrbiter;
import com.globbypotato.rockhounding_chemistry.machines.tile.devices.TEPowerGenerator;
import com.globbypotato.rockhounding_chemistry.machines.tile.devices.TESeasoningRack;
import com.globbypotato.rockhounding_chemistry.machines.tile.devices.TETransposer;
import com.globbypotato.rockhounding_chemistry.machines.tile.devices.TEWasteDumper;
import com.globbypotato.rockhounding_chemistry.machines.tile.devices.TEWaterPump;
import com.globbypotato.rockhounding_chemistry.machines.tile.pipelines.TEDustlinePump;
import com.globbypotato.rockhounding_chemistry.machines.tile.pipelines.TEGaslinePump;
import com.globbypotato.rockhounding_chemistry.machines.tile.pipelines.TEPipelinePump;
import com.globbypotato.rockhounding_chemistry.machines.tile.pipelines.TEPipelineValve;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEAuxiliaryEngine;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TECatalystRegenPipes;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TECentrifuge;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TECycloneSeparatorBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TECycloneSeparatorCap;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TECycloneSeparatorTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEDepositionBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEExhaustionValve;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEExtractorBalance;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEExtractorGlassware;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEExtractorReactor;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEExtractorStabilizer;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEFluidRouter;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEGanExpanderBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEGanExpanderTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEGasHolderTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEGasifierBurner;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEHeatExchangerTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TELabBlenderTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TELabOvenChamber;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TELeachingVatTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEMetalAlloyerTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEMineralSizerCabinet;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEMineralSizerCollector;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEMineralSizerTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEMineralSizerTransmission;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEPowderMixerTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEPrecipitationChamber;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEPrecipitationReactor;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEPullingCrucibleTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEReformerReactor;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEShredderBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEShredderTable;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TESpecimenCollector;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEStirredTankBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEStirredTankOut;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TETubularBedBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TETubularBedLow;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TETubularBedMid;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TETubularBedTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TETubularBedTop;
import com.globbypotato.rockhounding_chemistry.machines.tile.structure.TEUnloader;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEBufferTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEContainmentTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEEvaporationTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEFlotationTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEFluidCistern;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEFluidTank;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEGasHolderBase;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEMultivessel;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEPressureVessel;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEReinforcedCistern;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TESlurryDrum;
import com.globbypotato.rockhounding_chemistry.machines.tile.utilities.TEWashingTank;

import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModTileEntities {

	public static void registerTileEntities() {
		GameRegistry.registerTileEntity(TEMineralSizerCabinet.class, new ResourceLocation(Reference.MODID, TEMineralSizerCabinet.getName()));
		GameRegistry.registerTileEntity(TEMineralSizerTank.class, new ResourceLocation(Reference.MODID, TEMineralSizerTank.getName()));
		GameRegistry.registerTileEntity(TEPowerGenerator.class, new ResourceLocation(Reference.MODID, TEPowerGenerator.getName()));
		GameRegistry.registerTileEntity(TEMineralSizerCollector.class, new ResourceLocation(Reference.MODID, TEMineralSizerCollector.getName()));
		GameRegistry.registerTileEntity(TEFluidTank.class, new ResourceLocation(Reference.MODID, TEFluidTank.getName()));
		GameRegistry.registerTileEntity(TELabOvenController.class, new ResourceLocation(Reference.MODID, TELabOvenController.getName()));
		GameRegistry.registerTileEntity(TELabOvenChamber.class, new ResourceLocation(Reference.MODID, TELabOvenChamber.getName()));
		GameRegistry.registerTileEntity(TECentrifuge.class, new ResourceLocation(Reference.MODID, TECentrifuge.getName()));
		GameRegistry.registerTileEntity(TEUnloader.class, new ResourceLocation(Reference.MODID, TEUnloader.getName()));
		GameRegistry.registerTileEntity(TELabBlenderController.class, new ResourceLocation(Reference.MODID, TELabBlenderController.getName()));
		GameRegistry.registerTileEntity(TELabBlenderTank.class, new ResourceLocation(Reference.MODID, TELabBlenderTank.getName()));
		GameRegistry.registerTileEntity(TEProfilingBench.class, new ResourceLocation(Reference.MODID, TEProfilingBench.getName()));
		GameRegistry.registerTileEntity(TEEvaporationTank.class, new ResourceLocation(Reference.MODID, TEEvaporationTank.getName()));
		GameRegistry.registerTileEntity(TESeasoningRack.class, new ResourceLocation(Reference.MODID, TESeasoningRack.getName()));
		GameRegistry.registerTileEntity(TEServer.class, new ResourceLocation(Reference.MODID, TEServer.getName()));
		GameRegistry.registerTileEntity(TEGasExpanderController.class, new ResourceLocation(Reference.MODID, TEGasExpanderController.getName()));

		GameRegistry.registerTileEntity(TESlurryPondController.class, new ResourceLocation(Reference.MODID, TESlurryPondController.getName()));
		GameRegistry.registerTileEntity(TEReinforcedCistern.class, new ResourceLocation(Reference.MODID, TEReinforcedCistern.getName()));
		GameRegistry.registerTileEntity(TEGasifierController.class, new ResourceLocation(Reference.MODID, TEGasifierController.getName()));
		GameRegistry.registerTileEntity(TEGasifierBurner.class, new ResourceLocation(Reference.MODID, TEGasifierBurner.getName()));
		GameRegistry.registerTileEntity(TEGasPurifierController.class, new ResourceLocation(Reference.MODID, TEGasPurifierController.getName()));
		GameRegistry.registerTileEntity(TEAuxiliaryEngine.class, new ResourceLocation(Reference.MODID, TEAuxiliaryEngine.getName()));
		GameRegistry.registerTileEntity(TECycloneSeparatorBase.class, new ResourceLocation(Reference.MODID, TECycloneSeparatorBase.getName()));
		GameRegistry.registerTileEntity(TECycloneSeparatorTop.class, new ResourceLocation(Reference.MODID, TECycloneSeparatorTop.getName()));
		GameRegistry.registerTileEntity(TECycloneSeparatorCap.class, new ResourceLocation(Reference.MODID, TECycloneSeparatorCap.getName()));
		GameRegistry.registerTileEntity(TEFluidCistern.class, new ResourceLocation(Reference.MODID, TEFluidCistern.getName()));
		GameRegistry.registerTileEntity(TEPressureVessel.class, new ResourceLocation(Reference.MODID, TEPressureVessel.getName()));
		GameRegistry.registerTileEntity(TEAirCompressor.class, new ResourceLocation(Reference.MODID, TEAirCompressor.getName()));
		GameRegistry.registerTileEntity(TEHeatExchangerController.class, new ResourceLocation(Reference.MODID, TEHeatExchangerController.getName()));
		GameRegistry.registerTileEntity(TEHeatExchangerTop.class, new ResourceLocation(Reference.MODID, TEHeatExchangerTop.getName()));
		GameRegistry.registerTileEntity(TEGanExpanderBase.class, new ResourceLocation(Reference.MODID, TEGanExpanderBase.getName()));
		GameRegistry.registerTileEntity(TEGanExpanderTop.class, new ResourceLocation(Reference.MODID, TEGanExpanderTop.getName()));

		GameRegistry.registerTileEntity(TEGanController.class, new ResourceLocation(Reference.MODID, TEGanController.getName()));
		GameRegistry.registerTileEntity(TEGasCondenserController.class, new ResourceLocation(Reference.MODID, TEGasCondenserController.getName()));
		GameRegistry.registerTileEntity(TEMultivessel.class, new ResourceLocation(Reference.MODID, TEMultivessel.getName()));
		GameRegistry.registerTileEntity(TELeachingVatController.class, new ResourceLocation(Reference.MODID, TELeachingVatController.getName()));
		GameRegistry.registerTileEntity(TELeachingVatTank.class, new ResourceLocation(Reference.MODID, TELeachingVatTank.getName()));
		GameRegistry.registerTileEntity(TESpecimenCollector.class, new ResourceLocation(Reference.MODID, TESpecimenCollector.getName()));
		GameRegistry.registerTileEntity(TERetentionVatController.class, new ResourceLocation(Reference.MODID, TERetentionVatController.getName()));
		GameRegistry.registerTileEntity(TEExtractorController.class, new ResourceLocation(Reference.MODID, TEExtractorController.getName()));
		GameRegistry.registerTileEntity(TEExtractorReactor.class, new ResourceLocation(Reference.MODID, TEExtractorReactor.getName()));
		GameRegistry.registerTileEntity(TEElementsCabinetBase.class, new ResourceLocation(Reference.MODID, TEElementsCabinetBase.getName()));
		GameRegistry.registerTileEntity(TEElementsCabinetTop.class, new ResourceLocation(Reference.MODID, TEElementsCabinetTop.getName()));
		GameRegistry.registerTileEntity(TEExtractorGlassware.class, new ResourceLocation(Reference.MODID, TEExtractorGlassware.getName()));
		GameRegistry.registerTileEntity(TEExtractorBalance.class, new ResourceLocation(Reference.MODID, TEExtractorBalance.getName()));
		GameRegistry.registerTileEntity(TEReformerController.class, new ResourceLocation(Reference.MODID, TEReformerController.getName()));
		GameRegistry.registerTileEntity(TEReformerReactor.class, new ResourceLocation(Reference.MODID, TEReformerReactor.getName()));
		GameRegistry.registerTileEntity(TEExtractorStabilizer.class, new ResourceLocation(Reference.MODID, TEExtractorStabilizer.getName()));

		GameRegistry.registerTileEntity(TEMetalAlloyerController.class, new ResourceLocation(Reference.MODID, TEMetalAlloyerController.getName()));
		GameRegistry.registerTileEntity(TEMetalAlloyerTank.class, new ResourceLocation(Reference.MODID, TEMetalAlloyerTank.getName()));
		GameRegistry.registerTileEntity(TEMaterialCabinetBase.class, new ResourceLocation(Reference.MODID, TEMaterialCabinetBase.getName()));
		GameRegistry.registerTileEntity(TEMaterialCabinetTop.class, new ResourceLocation(Reference.MODID, TEMaterialCabinetTop.getName()));
		GameRegistry.registerTileEntity(TEDepositionBase.class, new ResourceLocation(Reference.MODID, TEDepositionBase.getName()));
		GameRegistry.registerTileEntity(TEDepositionController.class, new ResourceLocation(Reference.MODID, TEDepositionController.getName()));
		GameRegistry.registerTileEntity(TEGasHolderBase.class, new ResourceLocation(Reference.MODID, TEGasHolderBase.getName()));
		GameRegistry.registerTileEntity(TEGasHolderTop.class, new ResourceLocation(Reference.MODID, TEGasHolderTop.getName()));
		GameRegistry.registerTileEntity(TEPullingCrucibleController.class, new ResourceLocation(Reference.MODID, TEPullingCrucibleController.getName()));
		GameRegistry.registerTileEntity(TEPullingCrucibleTop.class, new ResourceLocation(Reference.MODID, TEPullingCrucibleTop.getName()));
		GameRegistry.registerTileEntity(TEOrbiter.class, new ResourceLocation(Reference.MODID, TEOrbiter.getName()));
		GameRegistry.registerTileEntity(TETransposer.class, new ResourceLocation(Reference.MODID, TETransposer.getName()));
		GameRegistry.registerTileEntity(TEFluidpedia.class, new ResourceLocation(Reference.MODID, TEFluidpedia.getName()));
		GameRegistry.registerTileEntity(TEWasteDumper.class, new ResourceLocation(Reference.MODID, TEWasteDumper.getName()));
		GameRegistry.registerTileEntity(TEFlotationTank.class, new ResourceLocation(Reference.MODID, TEFlotationTank.getName()));
		GameRegistry.registerTileEntity(TEContainmentTank.class, new ResourceLocation(Reference.MODID, TEContainmentTank.getName()));

		GameRegistry.registerTileEntity(TEWashingTank.class, new ResourceLocation(Reference.MODID, TEWashingTank.getName()));
		GameRegistry.registerTileEntity(TEExhaustionValve.class, new ResourceLocation(Reference.MODID, TEExhaustionValve.getName()));
		GameRegistry.registerTileEntity(TEWaterPump.class, new ResourceLocation(Reference.MODID, TEWaterPump.getName()));
		GameRegistry.registerTileEntity(TECatalystRegen.class, new ResourceLocation(Reference.MODID, TECatalystRegen.getName()));
		GameRegistry.registerTileEntity(TEDisposer.class, new ResourceLocation(Reference.MODID, TEDisposer.getName()));
		GameRegistry.registerTileEntity(TESlurryDrum.class, new ResourceLocation(Reference.MODID, TESlurryDrum.getName()));
		GameRegistry.registerTileEntity(TEBufferTank.class, new ResourceLocation(Reference.MODID, TEBufferTank.getName()));
		GameRegistry.registerTileEntity(TEStirredTankBase.class, new ResourceLocation(Reference.MODID, TEStirredTankBase.getName()));
		GameRegistry.registerTileEntity(TEStirredTankController.class, new ResourceLocation(Reference.MODID, TEStirredTankController.getName()));
		GameRegistry.registerTileEntity(TEStirredTankOut.class, new ResourceLocation(Reference.MODID, TEStirredTankOut.getName()));
		GameRegistry.registerTileEntity(TEPrecipitationController.class, new ResourceLocation(Reference.MODID, TEPrecipitationController.getName()));
		GameRegistry.registerTileEntity(TEPrecipitationChamber.class, new ResourceLocation(Reference.MODID, TEPrecipitationChamber.getName()));
		GameRegistry.registerTileEntity(TEPrecipitationReactor.class, new ResourceLocation(Reference.MODID, TEPrecipitationReactor.getName()));
		GameRegistry.registerTileEntity(TECatalystRegenPipes.class, new ResourceLocation(Reference.MODID, TECatalystRegenPipes.getName()));
		GameRegistry.registerTileEntity(TEPowderMixerController.class, new ResourceLocation(Reference.MODID, TEPowderMixerController.getName()));
		GameRegistry.registerTileEntity(TEPowderMixerTank.class, new ResourceLocation(Reference.MODID, TEPowderMixerTank.getName()));

		GameRegistry.registerTileEntity(TETubularBedBase.class, new ResourceLocation(Reference.MODID, TETubularBedBase.getName()));
		GameRegistry.registerTileEntity(TETubularBedLow.class, new ResourceLocation(Reference.MODID, TETubularBedLow.getName()));
		GameRegistry.registerTileEntity(TETubularBedMid.class, new ResourceLocation(Reference.MODID, TETubularBedMid.getName()));
		GameRegistry.registerTileEntity(TETubularBedTop.class, new ResourceLocation(Reference.MODID, TETubularBedTop.getName()));
		GameRegistry.registerTileEntity(TETubularBedTank.class, new ResourceLocation(Reference.MODID, TETubularBedTank.getName()));
		GameRegistry.registerTileEntity(TETubularBedController.class, new ResourceLocation(Reference.MODID, TETubularBedController.getName()));
		GameRegistry.registerTileEntity(TEFluidRouter.class, new ResourceLocation(Reference.MODID, TEFluidRouter.getName()));
		GameRegistry.registerTileEntity(TEMineralSizerController.class, new ResourceLocation(Reference.MODID, TEMineralSizerController.getName()));
		GameRegistry.registerTileEntity(TEMineralSizerTransmission.class, new ResourceLocation(Reference.MODID, TEMineralSizerTransmission.getName()));
		GameRegistry.registerTileEntity(TEShredderController.class, new ResourceLocation(Reference.MODID, TEShredderController.getName()));
		GameRegistry.registerTileEntity(TEShredderBase.class, new ResourceLocation(Reference.MODID, TEShredderBase.getName()));
		GameRegistry.registerTileEntity(TEShredderTable.class, new ResourceLocation(Reference.MODID, TEShredderTable.getName()));
		GameRegistry.registerTileEntity(TEPlanningTable.class, new ResourceLocation(Reference.MODID, TEPlanningTable.getName()));

		GameRegistry.registerTileEntity(TEPipelinePump.class, new ResourceLocation(Reference.MODID, TEPipelinePump.getName()));
		GameRegistry.registerTileEntity(TEPipelineValve.class, new ResourceLocation(Reference.MODID, TEPipelineValve.getName()));
		GameRegistry.registerTileEntity(TEGaslinePump.class, new ResourceLocation(Reference.MODID, TEGaslinePump.getName()));
		GameRegistry.registerTileEntity(TEDustlinePump.class, new ResourceLocation(Reference.MODID, TEDustlinePump.getName()));
	}
}